<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, nextTick } from 'vue';
import CvPreview from './components/CvPreview.vue';
import CvEditor from './components/CvEditor.vue';
import { defaultData } from './defaultData';
import type { CvData } from './types';
import { useLocale } from './composables/useLocale';

const cvData = ref<CvData>(defaultData);
const activeTab = ref('personal');
const lastSaved = ref<Date | null>(null);
const showSaveToast = ref(false);
// 预览显示缩放（仅影响屏幕显示，不影响 PDF；状态栏滑块与 Ctrl+滚轮共用）
const previewScale = ref(1);
// 预览 wrapper 的原始高度（未缩放），用于补偿外层占位容器高度，让滚动区匹配缩放后的视觉尺寸
const previewZoomRef = ref<HTMLElement | null>(null);
const previewOuterH = ref(0);
let resizeObserver: ResizeObserver | null = null;
const updateOuterH = () => {
  if (previewZoomRef.value) previewOuterH.value = previewZoomRef.value.offsetHeight * previewScale.value;
};
const { t, locale, toggleLocale, initLocale } = useLocale();

// Ctrl+滚轮缩放预览（0.5-2.0，步进 0.1）
const handleWheel = (e: WheelEvent) => {
  if (!e.ctrlKey) return;
  e.preventDefault();
  const step = e.deltaY < 0 ? 0.1 : -0.1;
  const next = Math.round((previewScale.value + step) * 10) / 10;
  previewScale.value = Math.min(2, Math.max(0.5, next));
};

// Initialize locale on mount
onMounted(() => {
  initLocale();
  // Try to load saved data
  const saved = localStorage.getItem('cv-generator-data');
  if (saved) {
    try {
      cvData.value = JSON.parse(saved);
    } catch (e) {
      console.warn('Failed to load saved data');
    }
  }
  startAutoSave();
  // 监听预览 wrapper 尺寸变化（分页变化、数据变化都会触发），同步外层占位高度
  nextTick(() => {
    if (previewZoomRef.value) {
      resizeObserver = new ResizeObserver(() => updateOuterH());
      resizeObserver.observe(previewZoomRef.value);
      updateOuterH();
    }
  });
});

watch(previewScale, () => updateOuterH());

onUnmounted(() => {
  if (autoSaveInterval) clearInterval(autoSaveInterval);
  if (resizeObserver) resizeObserver.disconnect();
});

let autoSaveInterval: number | null = null;

// Start auto-save
const startAutoSave = () => {
  if (autoSaveInterval) clearInterval(autoSaveInterval);
  autoSaveInterval = window.setInterval(() => {
    handleSave();
  }, 60000);
};

// Save to localStorage
const handleSave = () => {
  if (cvData.value.personal) {
    const now = new Date();
    const formattedDate = `${now.getFullYear()}.${String(now.getMonth() + 1).padStart(2, '0')}.${String(now.getDate()).padStart(2, '0')}`;
    cvData.value.personal.lastModifiedText = `${t('lastModified')}${formattedDate}`;
  }
  localStorage.setItem('cv-generator-data', JSON.stringify(cvData.value));
  lastSaved.value = new Date();
  showSaveToast.value = true;
  setTimeout(() => {
    showSaveToast.value = false;
  }, 2000);
};

const handleIconClick = (tabId: string) => {
  activeTab.value = tabId;
  if (tabId === 'settings') {
    const editor = document.querySelector('textarea');
    if (editor) editor.focus();
    return;
  }
  const el = document.getElementById(`section-${tabId}`);
  if (el) {
    el.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }
};

const handlePrint = () => {
  try {
    document.body.classList.add('is-printing');
    window.print();
    document.body.classList.remove('is-printing');
  } catch (e) {
    alert("Printing might be blocked in this preview window. Please use 'Open app in a new tab' (top right of the editor) and try again.");
  }
};

const handleExportJson = () => {
  const dataStr = JSON.stringify(cvData.value, null, 2);
  const blob = new Blob([dataStr], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `cv-data-${new Date().toISOString().split('T')[0]}.json`;
  a.click();
  URL.revokeObjectURL(url);
};

const handleImportJson = (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = (e) => {
    try {
      const parsedData = JSON.parse(e.target?.result as string);
      if (parsedData && parsedData.personal && parsedData.themeColor) {
        cvData.value = parsedData;

        // Reset the file input so the same file could theoretically be uploaded again
        if (target) target.value = '';
      } else {
        alert("Invalid JSON format. Make sure you are uploading a valid CV Data file generated by this tool.");
      }
    } catch (err) {
      alert("Error parsing JSON. Is the file corrupt?");
    }
  };
  reader.readAsText(file);
};

</script>

<template>
  <div
    class="flex flex-col h-screen print:h-auto bg-slate-50 text-slate-800 font-sans overflow-hidden print:overflow-visible print:block">
    <!-- Header Bar -->
    <header class="flex items-center justify-between px-6 py-3 bg-white border-b border-slate-200 no-print shrink-0">
      <div class="flex items-center gap-3">
        <h1 class="text-lg font-semibold tracking-tight text-slate-900">CV <span style="color: #01a3a4">Generator</span>
        </h1>
      </div>
      <div class="flex items-center gap-3">
        <button @click="toggleLocale"
          class="px-4 py-2 text-sm font-bold rounded-lg bg-slate-800 hover:bg-slate-900 text-white transition-colors shadow-md flex items-center gap-2">
          <i class="fa-solid fa-globe"></i>
          <span>{{ locale === 'en' ? '中文' : 'EN' }}</span>
        </button>
      </div>
    </header>

    <!-- Main Editor Layout -->
    <main class="flex flex-1 min-h-0 overflow-hidden print:overflow-visible print:block">
      <!-- Sidebar Navigation -->
      <nav
        class="w-16 border-r border-slate-200 bg-white flex flex-col items-center py-4 gap-6 no-print shrink-0 cursor-pointer select-none">
        <div @click="handleIconClick('personal')"
          :class="activeTab === 'personal' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'"
          class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Personal Info">
          <i class="fa-solid fa-user"></i>
        </div>
        <div @click="handleIconClick('education')"
          :class="activeTab === 'education' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'"
          class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Education & Skills">
          <i class="fa-solid fa-graduation-cap"></i>
        </div>
        <div @click="handleIconClick('employment')"
          :class="activeTab === 'employment' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'"
          class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Employment History">
          <i class="fa-solid fa-briefcase"></i>
        </div>
        <div @click="handleIconClick('articles')"
          :class="activeTab === 'articles' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'"
          class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors"
          title="Publications & Conferences">
          <i class="fa-solid fa-file-lines"></i>
        </div>
        <div @click="handleIconClick('other')"
          :class="activeTab === 'other' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'"
          class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Awards & Honors">
          <i class="fa-solid fa-star"></i>
        </div>
        <div @click="handleIconClick('custom')"
          :class="activeTab === 'custom' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'"
          class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Custom Sections">
          <i class="fa-solid fa-shapes"></i>
        </div>
        <div @click="handleIconClick('settings')"
          :class="activeTab === 'settings' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'"
          class="mt-auto w-10 h-10 rounded-lg flex items-center justify-center transition-colors"
          title="Settings & JSON Data">
          <i class="fa-solid fa-gear"></i>
        </div>
      </nav>

      <!-- Editor Pane -->
      <aside
        class="w-[450px] md:w-[500px] min-w-[350px] border-r border-slate-200 bg-white flex flex-col z-10 shrink-0 no-print shadow-sm h-full relative">
        <div class="h-14 border-b border-slate-200 bg-white flex justify-between items-center px-4 shrink-0">
          <h2 class="text-sm font-bold text-slate-700 capitalize w-20"><i
              class="fa-solid fa-pen-to-square text-[#01a3a4] mr-1.5 hidden sm:inline"></i> {{ activeTab }}</h2>
          <div class="flex items-center gap-2">
            <input type="file" id="import-json" accept=".json" class="hidden" @change="handleImportJson" />
            <label for="import-json"
              class="px-2 py-1.5 text-[11px] font-semibold text-slate-600 rounded bg-slate-100 hover:bg-slate-200 transition-colors shadow-sm cursor-pointer whitespace-nowrap">
              <i class="fa-solid fa-file-import mr-1"></i> <span class="hidden sm:inline">Import JSON</span>
            </label>
            <button @click="handleExportJson"
              class="px-2 py-1.5 text-[11px] font-semibold text-slate-600 rounded bg-slate-100 hover:bg-slate-200 transition-colors shadow-sm whitespace-nowrap">
              <i class="fa-solid fa-file-export mr-1"></i> <span class="hidden sm:inline">Export JSON</span>
            </button>
            <button @click="handlePrint"
              class="px-2 py-1.5 text-[11px] font-semibold text-white rounded bg-[#01a3a4] hover:bg-[#01a3a4]/90 transition-colors shadow-sm whitespace-nowrap border border-[#01a3a4]">
              <i class="fa-solid fa-file-pdf mr-1"></i> <span class="hidden sm:inline">PDF</span>
            </button>
            <button @click="handleSave"
              class="px-2 py-1.5 text-[11px] font-semibold text-white rounded bg-green-600 hover:bg-green-700 transition-colors shadow-sm whitespace-nowrap border border-green-600">
              <i class="fa-solid fa-save mr-1"></i> <span class="hidden sm:inline">Save</span>
            </button>
          </div>
        </div>
        <div class="flex-1 min-h-0 overflow-y-auto bg-slate-50 custom-scrollbar">
          <CvEditor v-model="cvData" :activeTab="activeTab" class="w-full border-none shadow-none" />
        </div>
      </aside>

      <!-- Preview Pane -->
      <section
        class="flex-1 bg-slate-200 py-4 md:py-8 overflow-auto print:overflow-visible print:w-full print:p-0 print:block custom-scrollbar flex flex-col items-center print:bg-white print:!absolute print:!top-0 print:!left-0 print:z-50"
        @wheel="handleWheel">
        <!-- w-full：横向排列时纸面超出窗口宽度，由本窗口（预览区）的滚动条横向滚动 -->
        <div class="print:w-full print:!m-0 print:block w-full preview-zoom-outer"
          :style="{ height: previewOuterH + 'px' }">
          <div ref="previewZoomRef" class="preview-zoom-wrapper"
            :style="{ transform: `scale(${previewScale})`, transformOrigin: 'top center' }">
            <!-- 注意：不要在此容器加 bg-white，否则页间空隙被白色填充，多张纸视觉上连成一张 -->
            <CvPreview :data="cvData" class="w-full print:w-full" />
          </div>
        </div>
      </section>

      <!-- Save Toast -->
      <Transition name="toast">
        <div v-if="showSaveToast"
          class="fixed bottom-4 right-4 bg-green-600 text-white px-4 py-2 rounded-lg shadow-lg flex items-center gap-2 z-50">
          <i class="fa-solid fa-check-circle"></i>
          <span class="text-sm font-medium">{{ t('savedSuccessfully') }}</span>
        </div>
      </Transition>
    </main>

    <!-- Status Bar -->
    <footer
      class="px-4 py-1.5 bg-white border-t border-slate-200 flex justify-between items-center text-[10px] text-slate-500 no-print shrink-0">
      <div class="flex items-center gap-4">
        <span>Mode: <span class="font-medium italic" style="color: #01a3a4">{{ t('visualDesign') }}</span></span>
        <span>{{ t('autoSave') }}: <span class="font-medium" style="color: #01a3a4">{{ t('active') }}</span></span>
      </div>
      <!-- 预览缩放控件（仅屏幕显示，不影响 PDF） -->
      <div class="flex items-center gap-2">
        <i class="fa-solid fa-magnifying-glass-minus text-slate-400"></i>
        <input type="range" v-model.number="previewScale" min="0.5" max="2" step="0.1"
          class="w-28 accent-[#01a3a4] cursor-pointer"
          :title="t('previewScaleHint')">
        <i class="fa-solid fa-magnifying-glass-plus text-slate-400"></i>
        <span class="font-mono text-slate-600 w-9 text-right">{{ Math.round(previewScale * 100) }}%</span>
        <button @click="previewScale = 1" :title="t('reset')"
          class="ml-1 px-1.5 py-0.5 text-[10px] rounded border border-slate-200 text-slate-500 hover:bg-slate-50 hover:text-[#01a3a4] hover:border-[#01a3a4]/30 transition-colors">
          <i class="fa-solid fa-rotate-left"></i>
        </button>
      </div>
    </footer>
  </div>
</template>

<style>
/* Add a custom scrollbar for the preview pane to make it look nicer */
.custom-scrollbar::-webkit-scrollbar {
  width: 10px;
  height: 10px;
}

.custom-scrollbar::-webkit-scrollbar-track {
  background: #e2e8f0;
}

.custom-scrollbar::-webkit-scrollbar-thumb {
  background: #94a3b8;
  border-radius: 5px;
}

.custom-scrollbar::-webkit-scrollbar-thumb:hover {
  background: #64748b;
}

/* Ensure background printing works */
@media print {
  @page {
    /* 页边距由每页 .page 的 padding 提供（见 index.css） */
    margin: 0 !important;
  }

  * {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }

  html,
  body,
  #app,
  main {
    width: 100% !important;
    max-width: 100% !important;
    background-color: white !important;
    margin: 0 !important;
    padding: 0 !important;
    overflow: visible !important;
    height: auto !important;
    min-height: auto !important;
    box-sizing: border-box !important;
  }

  /* 字体缩放由 CvPreview 的 pageCss 内联 zoom + padding 补偿处理，
     不在此重复声明 .page { zoom }，否则会与内联 zoom 叠加导致打印内容在 A4 内再次缩小 */

  /* 预览显示缩放仅用于屏幕，打印时强制重置 transform，避免影响 PDF 输出 */
  .preview-zoom-wrapper {
    transform: none !important;
  }
  .preview-zoom-outer {
    height: auto !important;
  }

  /* 增强分页控制 - 防止分页单元被分割到两页（条目级分页，与预览一致） */
  .page-unit {
    page-break-inside: avoid !important;
    break-inside: avoid !important;
    orphans: 10 !important;
    widows: 10 !important;
  }

  h2,
  h3 {
    page-break-after: avoid !important;
    page-break-before: avoid !important;
    break-after: avoid !important;
    break-before: avoid !important;
    orphans: 10 !important;
    widows: 10 !important;
  }

  /* 确保分页单元内所有子元素也不会被分割 */
  .page-unit>* {
    page-break-inside: avoid !important;
    break-inside: avoid !important;
  }

  /* 防止文章条目被分割 */
  .break-inside-avoid-page {
    break-inside: avoid !important;
    page-break-inside: avoid !important;
  }
}
</style>
