<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import CvPreview from './components/CvPreview.vue';
import CvEditor from './components/CvEditor.vue';
import { defaultData } from './defaultData';
import type { CvData } from './types';

const cvData = ref<CvData>(defaultData);
const activeTab = ref('personal');

const handleIconClick = (tabId: string) => {
  activeTab.value = tabId;
  if (tabId === 'settings') {
    const editor = document.querySelector('textarea');
    if (editor) editor.focus();
    return;
  }
  const el = document.getElementById(`section-${tabId}`);
  if (el) {
    el.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }
};

const handlePrint = () => {
  try {
    // Determine the exact dimensions to lock the scale and avoid bleeding
    // Setting body zoom to 1 or forcing container to not be constrained
    document.body.classList.add('is-printing');
    window.print();
    document.body.classList.remove('is-printing');
  } catch (e) {
    alert("Printing might be blocked in this preview window. Please use 'Open app in a new tab' (top right of the editor) and try again.");
  }
};

const handleExportJson = () => {
  const dataStr = JSON.stringify(cvData.value, null, 2);
  const blob = new Blob([dataStr], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `cv-data-${new Date().toISOString().split('T')[0]}.json`;
  a.click();
  URL.revokeObjectURL(url);
};

const handleImportJson = (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = (e) => {
    try {
      const parsedData = JSON.parse(e.target?.result as string);
      if (parsedData && parsedData.personal && parsedData.themeColor) {
        cvData.value = parsedData;
        
        // Reset the file input so the same file could theoretically be uploaded again
        if (target) target.value = '';
      } else {
        alert("Invalid JSON format. Make sure you are uploading a valid CV Data file generated by this tool.");
      }
    } catch (err) {
      alert("Error parsing JSON. Is the file corrupt?");
    }
  };
  reader.readAsText(file);
};

// Auto scaling for preview
const previewContainer = ref<HTMLElement | null>(null);
const previewScale = ref(1);
let resizeObserver: ResizeObserver | null = null;

onMounted(() => {
  resizeObserver = new ResizeObserver((entries) => {
    for (let entry of entries) {
       const wrapperWidth = entry.contentRect.width;
       // 210mm paper width is exactly ~794px. We add 64px max margin minimum padding constraint
       if (wrapperWidth < 858) {
         previewScale.value = (wrapperWidth - 32) / 794;
       } else {
         previewScale.value = 1;
       }
    }
  });
  if (previewContainer.value) {
    resizeObserver.observe(previewContainer.value);
  }
});

onUnmounted(() => {
  if (resizeObserver) resizeObserver.disconnect();
});
</script>

<template>
  <div class="flex flex-col h-screen print:h-auto bg-slate-50 text-slate-800 font-sans overflow-hidden print:overflow-visible print:block">
    <!-- Header Bar -->
    <header class="flex items-center justify-between px-6 py-3 bg-white border-b border-slate-200 no-print shrink-0">
      <div class="flex items-center gap-3">
        <h1 class="text-lg font-semibold tracking-tight text-slate-900">CV <span style="color: #01a3a4">Generator</span></h1>
      </div>
      <div class="flex items-center gap-3 text-sm text-slate-500 font-medium">
        Personal CV Generator
      </div>
    </header>

    <!-- Main Editor Layout -->
    <main class="flex flex-1 min-h-0 overflow-hidden print:overflow-visible print:block">
      <!-- Sidebar Navigation -->
      <nav class="w-16 border-r border-slate-200 bg-white flex flex-col items-center py-4 gap-6 no-print shrink-0 cursor-pointer select-none">
        <div @click="handleIconClick('personal')" :class="activeTab === 'personal' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'" class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Personal Info">
          <i class="fa-solid fa-user"></i>
        </div>
        <div @click="handleIconClick('education')" :class="activeTab === 'education' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'" class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Education & Skills">
          <i class="fa-solid fa-graduation-cap"></i>
        </div>
        <div @click="handleIconClick('employment')" :class="activeTab === 'employment' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'" class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Employment History">
          <i class="fa-solid fa-briefcase"></i>
        </div>
        <div @click="handleIconClick('articles')" :class="activeTab === 'articles' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'" class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Publications & Conferences">
          <i class="fa-solid fa-file-lines"></i>
        </div>
        <div @click="handleIconClick('other')" :class="activeTab === 'other' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'" class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Awards & Honors">
          <i class="fa-solid fa-star"></i>
        </div>
        <div @click="handleIconClick('custom')" :class="activeTab === 'custom' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'" class="w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Custom Sections">
          <i class="fa-solid fa-shapes"></i>
        </div>
        <div @click="handleIconClick('settings')" :class="activeTab === 'settings' ? 'bg-[#e6f6f6] text-[#01a3a4] text-lg' : 'text-slate-400 hover:bg-slate-50 text-lg'" class="mt-auto w-10 h-10 rounded-lg flex items-center justify-center transition-colors" title="Settings & JSON Data">
          <i class="fa-solid fa-gear"></i>
        </div>
      </nav>

      <!-- Editor Pane -->
      <aside class="w-[450px] md:w-[500px] min-w-[350px] border-r border-slate-200 bg-white flex flex-col z-10 shrink-0 no-print shadow-sm h-full relative">
        <div class="h-14 border-b border-slate-200 bg-white flex justify-between items-center px-4 shrink-0">
           <h2 class="text-sm font-bold text-slate-700 capitalize w-20"><i class="fa-solid fa-pen-to-square text-[#01a3a4] mr-1.5 hidden sm:inline"></i> {{ activeTab }}</h2>
           <div class="flex items-center gap-2">
             <input type="file" id="import-json" accept=".json" class="hidden" @change="handleImportJson" />
             <label for="import-json" class="px-2 py-1.5 text-[11px] font-semibold text-slate-600 rounded bg-slate-100 hover:bg-slate-200 transition-colors shadow-sm cursor-pointer whitespace-nowrap">
               <i class="fa-solid fa-file-import mr-1"></i> <span class="hidden sm:inline">Import JSON</span>
             </label>
             <button @click="handleExportJson" class="px-2 py-1.5 text-[11px] font-semibold text-slate-600 rounded bg-slate-100 hover:bg-slate-200 transition-colors shadow-sm whitespace-nowrap">
               <i class="fa-solid fa-file-export mr-1"></i> <span class="hidden sm:inline">Export JSON</span>
             </button>
             <button @click="handlePrint" class="px-2 py-1.5 text-[11px] font-semibold text-white rounded bg-[#01a3a4] hover:bg-[#01a3a4]/90 transition-colors shadow-sm whitespace-nowrap border border-[#01a3a4]">
               <i class="fa-solid fa-file-pdf mr-1"></i> <span class="hidden sm:inline">PDF</span>
             </button>
           </div>
        </div>
        <div class="flex-1 min-h-0 overflow-y-auto bg-slate-50 custom-scrollbar">
          <CvEditor v-model="cvData" :activeTab="activeTab" class="w-full border-none shadow-none" />
        </div>
      </aside>

      <!-- Preview Pane -->
      <section ref="previewContainer" class="flex-1 bg-slate-200 py-4 md:py-8 overflow-y-auto print:overflow-visible print:w-full print:p-0 print:block custom-scrollbar flex flex-col items-center print:bg-white print:!absolute print:!top-0 print:!left-0 print:z-50">
        <div class="origin-top print:!transform-none print:w-full print:!m-0 print:block w-[210mm]" :style="{ transform: `scale(${previewScale})`, marginBottom: previewScale < 1 ? `-${(1 - previewScale) * 100}%` : '0' }">
          <CvPreview :data="cvData" class="shadow-2xl print:shadow-none bg-white w-full print:w-full" />
        </div>
      </section>
    </main>

    <!-- Status Bar -->
    <footer class="px-4 py-1.5 bg-white border-t border-slate-200 flex justify-between items-center text-[10px] text-slate-500 no-print shrink-0">
      <div class="flex items-center gap-4">
        <span>Mode: <span class="font-medium italic" style="color: #01a3a4">Visual Design</span></span>
        <span>Auto-save: <span class="font-medium" style="color: #01a3a4">Active</span></span>
      </div>
      <div class="flex gap-4">
        <span>FontAwesome: Loaded</span>
        <span>Vue v3</span>
      </div>
    </footer>
  </div>
</template>

<style>
/* Add a custom scrollbar for the preview pane to make it look nicer */
.custom-scrollbar::-webkit-scrollbar {
  width: 10px;
}
.custom-scrollbar::-webkit-scrollbar-track {
  background: #e2e8f0;
}
.custom-scrollbar::-webkit-scrollbar-thumb {
  background: #94a3b8;
  border-radius: 5px;
}
.custom-scrollbar::-webkit-scrollbar-thumb:hover {
  background: #64748b;
}

/* Ensure background printing works */
@media print {
  @page {
    margin: 0.5cm;
  }
  * {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  html, body, #app, main {
    width: 100% !important;
    max-width: 100% !important;
    background-color: white !important;
    margin: 0 !important;
    padding: 0 !important;
    overflow: visible !important;
    height: auto !important;
    min-height: auto !important;
    box-sizing: border-box !important;
  }
}
</style>
